INSERT INTO BOOK (BOOK_ID, TITLE, AUTHOR, PUBLISHED_DATE, PRICE, DESCRIPTION)
VALUES (1, 'Book 1', 'Author 1', '2024-10-03', 1000 , 'Book1 description');

INSERT INTO BOOK (BOOK_ID, TITLE, AUTHOR, PUBLISHED_DATE, PRICE, DESCRIPTION)
VALUES (2, 'Book 2', 'Author 1', '2024-10-03', 100 , 'Book2 description');

INSERT INTO BOOK (BOOK_ID, TITLE, AUTHOR, PUBLISHED_DATE, PRICE, DESCRIPTION)
VALUES (3, 'Book 3', 'Author 2', '2024-10-03', 400 , 'Book3 description');
